apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-test-nfs
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: psc
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod-ngix
  labels: 
    app : nginx
spec:
  volumes:
    - name: my-pod-storage
      persistentVolumeClaim:
        claimName: pvc-test-nfs
  containers:
    - name: demo-pod-ngix-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-pod-storage
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service-nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
