apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsphere-with-tanzu-pv-dirk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kubernetes-gold-storage-policy
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: tanzu-demo-pod-ngix
  labels: 
    app : nginx
spec:
  volumes:
    - name: my-pod-storage
      persistentVolumeClaim:
        claimName: vsphere-with-tanzu-pv-dirk
  containers:
    - name: tanzu-demo-pod-ngix-container
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-pod-storage
      command: ["cd"]
      args: ["/usr/share/nginx/html"]
      command: ["curl"]
      args: ["https://raw.githubusercontent.com/DirkDevOpsDemos/TanzuSampleApp/main/index.html -o index.html"]
---
apiVersion: v1
kind: Service
metadata:
  name: tanzu-demo-service-nginx
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
