apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsphere-with-tanzu-pvc-nfs-rwx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kubernetes-nfs-policy
  resources:
    requests:
      storage: 1Gi
