apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsphere-with-tanzu-pvc-vsan-rwx
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kubernetes-gold-storage-policy
  resources:
    requests:
      storage: 1Gi
