apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vsphere-with-tanzu-pv-dirk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: kubernetes-gold-storage-policy
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tanzu-demo-deployment-ngix
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: tanzu-demo-deployment-ngix-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-pod-storage
        command: ["cd"]
        args: ["/usr/share/nginx/html"]
        command: ["curl"]
        args: ["https://raw.githubusercontent.com/DirkDevOpsDemos/TanzuSampleApp/main/index.html -o index.html"]
